version: '3.4'
services:
  jamespc:
    build: ./jamespc
    cap_add:
      - LINUX_IMMUTABLE

  randalpc:
    build: ./randalpc

  xssbot:
    build: ./xssbot

  startingpoint:
    build: ./startingpoint
    ports:
      - 2222:22

  tompc:
    build: ./tompc

  jwtbot:
    build: ./tompc/discordbot

  finale:
    build: ./finale
