#!/usr/bin/env python3

import util
import sys

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Usage: checkstats <mem|proc|disk>")
        exit(1)

    if sys.argv[1] == "mem":
        util.checkmem()
    elif sys.argv[1] == "proc":
        util.checkproc()
    elif sys.argv[1] == "disk":
        util.checkdisk()
